[toolchain]
anchor_version = "0.30.0"
solana_version = "1.18.17"
[features]
resolution = true
skip-lint = false

[programs.localnet]
uncx-solana-lp-locker = "GsSCS3vPWrtJ5Y9aEVVT65fmrex5P5RGHXdZvsdbWgfo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://quick-ancient-film.solana-mainnet.quiknode.pro/8bc4870cba05e49a4030e48e2162000b06ae964b"
# cluster = "Localnet"
wallet = "/Users/aaran/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
